openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tallii Platform
  description: Platform Service for tallii.io
  contact:
    name: Tallii Engineering
    email: adam.aho@hey.com
    url: https://tallii.io

paths:
  /v1/login:
    post:
      operationId: postLogin
      summary: accepts an email and password and returns an access token and the user info.
      requestBody:
        description: login model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestModel'
      responses:
        200:
          description: access token and user info
          $ref: '#/components/responses/LoginSignupResponse'
        401:
          description: the provided creds are invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/signup:
    post:
      operationId: postSignup
      summary: accepts an email, password and username and returns an access token and the user info.
      requestBody:
        description: signup model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequestModel'
      responses:
        200:
          description: access token and user info
          $ref: '#/components/responses/LoginSignupResponse'
        401:
          description: the provided creds are invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/authorize:
    get:
      operationId: getAuthorize
      summary: authorizes the jwt token to make sure it hasnt expired
      security:
        - bearerAuth: []
      responses:
        200:
          description: access token and user info
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/me:
    get:
      operationId: getMe
      summary: gets the user info of the currently logged in user
      security:
        - bearerAuth: []
      responses:
        200:
          description: the user info of the currently logged in user
          $ref: '#/components/responses/GetMeResponse'
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
    put:
      operationId: updateMe
      summary: updates the currently logged in users profile
      security:
        - bearerAuth: []
      requestBody:
        description: the user info to update with
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequestModel'
      responses:
        200:
          description: the user info of the currently logged in user
          $ref: '#/components/responses/GetMeResponse'
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/scoreboards:
    post:
      operationId: createScoreboard
      summary: creates a scoreboard
      security:
        - bearerAuth: []
      requestBody:
        description: create scoreboard model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScoreboardRequestModel'
      responses:
        200:
          description: the created scoreboard
          $ref: '#/components/responses/CreateScoreboardResponse'
        401:
          description: the provided creds are invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/me/scoreboards:
    get:
      operationId: getMyScoreboards
      summary: gets the scoreboards of the currently logged in user
      security:
        - bearerAuth: []
      responses:
        200:
          description: the scoreboards of the currently logged in user
          $ref: '#/components/responses/GetScoreboardsResponse'
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/scoreboards/{scoreboard_id}:
    parameters:
      - in: path
        name: scoreboard_id
        schema:
          type: integer
        required: true
        description: the specific scoreboard_id
    get:
      operationId: getScoreboard
      summary: gets a specific scoreboard
      security:
        - bearerAuth: []
      responses:
        200:
          description: the specific scoreboard
          $ref: '#/components/responses/GetScoreboardResponse'
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/InternalServerError'
    delete:
      operationId: deleteScoreboard
      summary: deletes a specific scoreboard
      security:
        - bearerAuth: []
      responses:
        200:
          description: the specific scoreboard
        401:
          description: the provided token is invalid
          $ref: '#/components/responses/Unauthorized'
        403:
          description: the user is not allowed to perform this action
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/InternalServerError'
  /v1/teams/{team_id}:
    parameters:
      - in: path
        name: team_id
        schema:
          type: integer
        required: true
        description: the specific team_id
    get:
      operationId: getTeam
      summary: gets a specific team
      security:
        - bearerAuth: []
      responses:
        200:
          description: access token and user info
          $ref: '#/components/responses/GetTeamResponse'
        401:
          description: the provided creds are invalid
          $ref: '#/components/responses/Unauthorized'
        403:
          description: the user is not allowed to perform this action
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/InternalServerError'
    put:
      operationId: updateTeam
      summary: updates the specific team
      security:
        - bearerAuth: []
      requestBody:
        description: update team model
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTeamRequestModel'
      responses:
        200:
          description: access token and user info
          $ref: '#/components/responses/GetTeamResponse'
        401:
          description: the provided creds are invalid
          $ref: '#/components/responses/Unauthorized'
        403:
          description: the user is not allowed to perform this action
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'
    GetMeResponse:
      description: the user info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserModel'
    LoginSignupResponse:
      description: access token and user info
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginSignupResponseModel'
    GetScoreboardsResponse:
      description: scoreboards
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              $ref: '#/components/schemas/ScoreboardModel'
    GetScoreboardResponse:
      description: scoreboard
      content:
        application/json:
          schema:
            type: object
            $ref: '#/components/schemas/ScoreboardModel'
    CreateScoreboardResponse:
      description: scoreboard
      content:
        application/json:
          schema:
            type: object
            $ref: '#/components/schemas/ScoreboardModel'
    GetTeamResponse:
      description: team
      content:
        application/json:
          schema:
            type: object
            $ref: '#/components/schemas/TeamModel'
  schemas:
    ErrorModel:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    LoginRequestModel:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SignupRequestModel:
      type: object
      properties:
        email:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - email
        - username
        - password
    LoginSignupResponseModel:
      type: object
      properties:
        access_token:
          type: string
        user:
          type: object
          $ref: '#/components/schemas/UserModel'
      required:
        - access_token
        - user
    UserModel:
      type: object
      properties:
        user_id:
          type: integer
        username:
          type: string
        email:
          type: string
        avatar_background:
          type: string
        avatar_emoji:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - user_id
        - username
        - email
        - avatar_background
        - avatar_emoji
        - created_at
    UpdateUserRequestModel:
      type: object
      properties:
        username:
          type: string
        avatar_background:
          type: string
        avatar_emoji:
          type: string
      required:
        - username
        - avatar_background
        - avatar_emoji
    TeamModel:
      type: object
      properties:
        team_id:
          type: integer
        scoreboard_id:
          type: integer
        name:
          type: string
        score:
          type: integer
        created_at:
          type: string
          format: date-time
      required:
        - team_id
        - scoreboard_id
        - name
        - score
        - created_at
    ScoreboardModel:
      type: object
      properties:
        scoreboard_id:
          type: integer
        name:
          type: string
        game:
          type: string
        created_by:
          $ref: '#/components/schemas/UserModel'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        teams:
          type: array
          items:
            $ref: '#/components/schemas/TeamModel'
      required:
        - scoreboard_id
        - name
        - game
        - created_by
        - created_at
        - updated_at
        - teams
    UpdateTeamRequestModel:
      type: object
      properties:
        name:
          type: string
        score:
          type: integer
    CreateScoreboardRequestModel:
      type: object
      properties:
        name:
          type: string
        game:
          type: string
        teams:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
            required:
              - name
      required:
        - name
        - game
        - teams


    


