@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRhbS5haG9AZ21haWwuY29tIiwiZXhwIjoxNjQzMzE2NjU5fQ.IAEVjTDAg1KoWqs699TXGviaqi0ZD4jvSQSBJykDGnY


# Endpoint that should be called to verify a jwt
GET http://localhost:6000/v1/authorize HTTP/1.1
Authorization: Bearer {{ token }}
content-type: application/json


###

POST http://localhost:6000/v1/login HTTP/1.1
content-type: application/json

{
  "email": "adam.aho@gmail.com",
  "password": "bubba1"
}

###

POST http://localhost:6000/v1/signup HTTP/1.1
content-type: application/json

{
  "username": "adam",
  "email": "adam.aho@gmail.com",
  "password": "bubba1"
}

###

GET http://localhost:6000/v1/scoreboards HTTP/1.1
Authorization: Bearer {{ token }}

###

GET http://localhost:6000/v1/scoreboards/4 HTTP/1.1
Authorization: Bearer {{ token }}


###

POST http://localhost:6000/v1/scoreboards HTTP/1.1
Authorization: Bearer {{ token }}

{
  "name": "christmas 2021",
  "game": "euchure",
  "teams": [
    {
      "name": "team1"
    },
    {
      "name": "team2"
    }
  ]
}


